### ISSUE TITLE
Disabling TabZolo closes currently open tab.

### ISSUE THREAD

**Issue by dasmall** [dasmall/TabZolo#2]
Currently open tab should be maintained and previously closed tabs restored.

**Comment by dasmall** [comment]
Welp. That was easy.

https://github.com/dasmall/TabZolo/commit/87d4aa7d44063a6db1223abf1f9cb555bf900eda

**Comment by Tonkpils** [comment]
You should just delete the code instead of commenting it out. No point on keeping that code around in the repo. Also, you can close a github issue from a commit by typing `closes #2`
