### ISSUE TITLE
Pinned tabs should stay pinned once tz is released

### ISSUE THREAD

**Issue by kunald112** [dasmall/TabZolo#4]
Hey guys, awesome idea! I love the concept. I've used tz a few times, and found that when tz is released, i.e. equivalent of deactivating it, the pinned tabs become regular tabs, and I need to go back and pin them. I would think you'd want the pinned tabs to stay pinned once tz is deactivated. 

Good luck!

**Comment by Tonkpils** [comment]
Good point, I have an idea of how to go about doing this and you're right, the properties of a tab should be kept when toggling the extension.

**Comment by dasmall** [comment]
@kunald112, thanks so much for catching that! As you can probably guess, @Tonkpils and I don't exactly use that feature so it completed slipped out scope.

We've enhanced tz with your comment in mind and you should be seeing it in the Chrome Web Store soon. It's version 1.0.3.

**Comment by kunald112** [comment]
Very cool! Thanks for getting this fixed. Look forward to the updated version. Now, if only I could get my team at work to get bugs fixed this quickly :)
